export const itemInfoDefs = [
      {
            officialCode: "HFD",
            code: "FD",
            name: "Het Financieele Dagblad",
            order: 1,
            needsPreparation: true,
            needsDelivery: true,
            needsPickup: false,
      },
      {
            officialCode: "NRC",
            code: "NRC",
            name: "NRC",
            order: 2,
            needsPreparation: true,
            needsDelivery: true,
            needsPickup: false,
      },
      {
            officialCode: "TEL",
            code: "TEL",
            name: "Telegraaf",
            order: 3,
            needsPreparation: true,
            needsDelivery: true,
            needsPickup: false,
      },
      
      {
            officialCode: "TR",
            code: "TR",
            name: "Trouw",
            order: 4,
            needsPreparation: true,
            needsDelivery: true,
            needsPickup: false,
      },
      {
            officialCode: "VK",
            code: "VK",
            name: "Volkskrant",
            order: 5,
            needsPreparation: true,
            needsDelivery: true,
            needsPickup: false,
      },
      {
            officialCode: "TT HE",
            code: "HE",
            name: "Tubantia Hengelo",
            order: 6,
            needsPreparation: false,
            needsDelivery: true,
            needsPickup: false,
      },
      {
            officialCode: "TT AM",
            code: "AM",
            name: "Tubantia Almelo",
            order: 7,
            needsPreparation: true,
            needsDelivery: true,
            needsPickup: false,
      },
      {
            officialCode: "AD NL",
            code: "AD",
            name: "Algemeen Dagblad",
            order: 8,
            needsPreparation: true,
            needsDelivery: true,
            needsPickup: false,
      },
      {
            officialCode: null,
            code: "pup",
            name: "Pick-up Weekend Batch",
            order: -1,
            needsPreparation: false,
            needsDelivery: false,
            needsPickup: true,
      },
];